# playbook.yml
- hosts: all
  become: yes
  tasks:
    - name: Wait for dpkg lock
      shell: |
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
          sleep 1
        done
      changed_when: false
      
    - name: Wait for apt lock
      shell: |
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          sleep 1
        done
      changed_when: false

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      register: result
      until: result is succeeded
      retries: 10
      delay: 15

    - name: Enable and start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Enable UFW and allow HTTP
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Deploy simple HTML page
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Deployed via An sible</h1>"
